// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCth5MLtbfEC-ehPci0JPn0ZLKwysDQgM',
    appId: '1:354407385313:web:b4d2e4fc44669017998fa0',
    messagingSenderId: '354407385313',
    projectId: 'fireside-b52e6',
    authDomain: 'fireside-b52e6.firebaseapp.com',
    databaseURL: 'https://fireside-b52e6-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-b52e6.appspot.com',
    measurementId: 'G-988QYFQ02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZNnP-SpVVs5nRnWKNgkBiInfw0AsImw',
    appId: '1:354407385313:android:3006307fbda06f04998fa0',
    messagingSenderId: '354407385313',
    projectId: 'fireside-b52e6',
    databaseURL: 'https://fireside-b52e6-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-b52e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB63GbclQblIyX7EUooKHmmn4gMTP_RZ6Q',
    appId: '1:354407385313:ios:cfb6f2d55351882f998fa0',
    messagingSenderId: '354407385313',
    projectId: 'fireside-b52e6',
    databaseURL: 'https://fireside-b52e6-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-b52e6.appspot.com',
    iosBundleId: 'com.ostad.ostad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB63GbclQblIyX7EUooKHmmn4gMTP_RZ6Q',
    appId: '1:354407385313:ios:bcc5f19e4f6be5de998fa0',
    messagingSenderId: '354407385313',
    projectId: 'fireside-b52e6',
    databaseURL: 'https://fireside-b52e6-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-b52e6.appspot.com',
    iosBundleId: 'com.ostad.ostad.RunnerTests',
  );
}
